#!/usr/bin/env ruby

require "lock_diff"
require "lock_diff/cli/option_parser"

options = LockDiff::Cli::OptionParser.parse(ARGV, require_flags: %i(repository))
LockDiff.run_by_latest_tachikoma(options)
