#!/usr/bin/env ruby

require "lock_diff"
require "optparse"

options = {
  post_comment: false
}
opt = OptionParser.new

opt.on('-r', '--repository=REPOSITORY', 'required. Like as "user/repository"') { |v| options[:repository] = v }
opt.on('-n', '--number=PULL_REQUEST_NUMBER', 'required') { |v| options[:number] = v }
opt.on('--post-comment=true or false', 'dafault=false') { |v| options[:post_comment] = v }
opt.parse!

unless options[:repository] && options[:number]
  $stdout.puts opt.help
else
  LockDiff.run(options)
end
